WebUI/ViewModels/BlogCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YazilimBlogApp.Entities.Concrete;

namespace YazilimBlogApp.WebUI.ViewModels
{
    public class BlogCategoryViewModel
    {
        public Blog Blog { get; set; }
        public int CountCategory { get; set; }
        public Category Category { get; set; }
        public IEnumerable<Blog> Blogs { get; set; }
        public IEnumerable<Category> Categories { get; set; }
   
    }
}

WebUI/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using YazilimBlogApp.BusinessLayer.Abstract;
using YazilimBlogApp.Entities.Concrete;

namespace YazilimBlogApp.WebUI.Controllers
{
    public class BlogController : Controller
    {
        private IBlogService _blogService;
        private ICategoryService _categoryService;

        public BlogController(IBlogService blogService, ICategoryService categoryService)
        {
            _blogService = blogService;
            _categoryService = categoryService;
        }

        //Methods
        public void ListCategory()
        {
            ViewBag.ListCategory = new SelectList(_categoryService.GetAll().Data, "Id", "Name");
        }

        //Actions
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {
            return View(_blogService.GetAll().Data);
        }

        public IActionResult Create()
        {
            ListCategory();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Blog entity,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                   var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                        entity.Image = file.FileName;
                    }
                }
                _blogService.Add(entity);
                return RedirectToAction("List");
            }
            return View(entity);
        }

        public IActionResult Edit(int id)
        {
            ListCategory();
            return View(_blogService.GetById(id).Data);
        }

        [HttpPost]
        public IActionResult Edit(Blog entity)
        {
            if (ModelState.IsValid)
            {
                _blogService.Update(entity);
                return RedirectToAction("List");
            }
            else
            {
                return View(entity);
            }  
        }

        public IActionResult Delete(Blog entity)
        {
            _blogService.Delete(_blogService.GetById(entity.Id).Data);
            return RedirectToAction("List");
        }

        public IActionResult Details(int id)
        {
            return View(_blogService.GetById(id).Data);
        }
    }
}   

WebUI/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using YazilimBlogApp.BusinessLayer.Abstract;
using YazilimBlogApp.Entities.Concrete;

namespace YazilimBlogApp.WebUI.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        //Actions
        public IActionResult List() => View(_categoryService.GetAll().Data);

        public IActionResult Create() => View();

        [HttpPost]
        public IActionResult Create(Category entity)
        {
            if (ModelState.IsValid)
            {
                _categoryService.Add(entity);
                return RedirectToAction("List");
            }
            return View(entity);
        }

        public IActionResult Edit(int id) => View(_categoryService.GetById(id).Data);
        [HttpPost]
        public IActionResult Edit(Category entity)
        {
            if (ModelState.IsValid)
            {
                _categoryService.Update(entity);
                return RedirectToAction("List");
            }
            else
            {
                return View(entity);
            }
        }

        public IActionResult Delete(Category entity)
        {
            _categoryService.Delete(_categoryService.GetById(entity.Id).Data);
            return RedirectToAction("List");
        }
    }
}

WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using YazilimBlogApp.BusinessLayer.Abstract;

namespace YazilimBlogApp.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IBlogService _blogService;
        private ICategoryService _categoryService;

        public HomeController(IBlogService blogService, ICategoryService categoryService)
        {
            _blogService = blogService;
            _categoryService = categoryService;
        }

        //Actions
        public IActionResult Index(int id,string search)
        {
            if (!string.IsNullOrEmpty(search))
            {
                var querySearch = _blogService.GetAll().Data.Where(x => x.Title.Contains(search));
                return View(querySearch);
            }
            //BlogsCategoryViewModel model = new BlogsCategoryViewModel();
            //model.Blogs = _blogService.GetAll();
           
            return View(_blogService.GetAll().Data.Where(x=>x.IsHome && x.IsApproved));
        }
        public IActionResult Category(int id)
        {
            return View(_blogService.GetAll().Data.Where(x => x.CategoryId == id && x.IsApproved));
        }

        public IActionResult Details(int id)
        {
            return View(_blogService.GetById(id).Data);
        }
    }
}

WebUI/Views/Blog/Create.cshtml
@model  Blog

    <form method="post" enctype="multipart/form-data">
        <div asp-validation-summary="All"></div>
        <div class="container">
            <div class="card card-primary card-outline">
                <div class="card-body">

                    <div class="form-check">
                        <input class="form-check-input" asp-for="IsHome" />
                        <label asp-for="IsHome" class="form-check-label"></label>
                    </div>

                    <div class="form-check">
                        <input class="form-check-input" asp-for="IsApproved" />
                        <label asp-for="IsApproved" class="form-check-label"></label>
                    </div>

                    <div class="card-text form-group">
                        <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.ListCategory">
                            <option disabled selected>Select Category</option>
                        </select>
                    </div>

                    <div class="card-text form-group">
                        <label asp-for="Title"></label>
                        <input asp-for="Title" class="form-control" />
                    </div>

                    <div class="card-text form-group">
                        <label asp-for="Description"></label>
                        <input asp-for="Description" class="form-control" />
                    </div>

                    <div class="card-text form-group">
                        <label asp-for="Content"></label>
                        <input asp-for="Content" class="form-control" />
                    </div>

                    <div class="card-text form-group">
                        <label asp-for="Image"></label>
                        <input type="file" name="file" id="file" class="form-control" />
                    </div>

                    <div class="card-text form-group">
                        <label asp-for="Date"></label>
                        <input asp-for="Date" class="form-control" />
                    </div>

                    <input type="submit" value="Add" class="btn btn-success text-right" />
                </div>
            </div>
        </div>
    </form>

WebUI/Views/Blog/Details.cshtml
@model Blog

<div class="card card-primary card-outline">
    <div class="card-body">
        <p class="card-text">@Model.Title</p> 
        <p class="card-text">@Model.Description</p>
        <p class="card-text">@Html.Raw(Model.Content)</p>
        <div>
            <img src="~/img/@Model.Image" alt="@Model.Title"/>
        </div>
        <p class="card-footer text-muted">
            @Model.Date
        </p>
    </div>
</div>

WebUI/Views/Blog/Edit.cshtml
@model Blog

@section ckEditors{
    <script src="/modules/ckeditor/ckeditor.js"></script>
    <script>
    CKEDITOR.replace("Content");
    </script>
}
<form method="post" enctype="multipart/form-data">
    <input type="hidden" asp-for="Image" />
    <div class="container">
        <div class="card card-primary card-outline">
            <div class="card-body">

                <div class="form-check">
                    <input class="form-check-input" asp-for="IsHome" />
                    <label asp-for="IsHome" class="form-check-label"></label>
                </div>

                <div class="form-check">
                    <input class="form-check-input" asp-for="IsApproved" />
                    <label asp-for="IsApproved" class="form-check-label"></label>
                </div>

                <div class="card-text form-group">
                    <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.ListCategory"></select>
                </div>

                <div class="card-text form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" />
                </div>

                <div class="card-text form-group">
                    <label asp-for="Description"></label>
                    <input asp-for="Description" class="form-control" />
                </div>

                <div class="card-text form-group">
                    <img src="~/img/@Model.Image" alt="@Model.Image" width="160" />
                    <input type="file" name="file" id="file" class="form-control" />
                </div>

                <div class="card-text form-group">
                    <label asp-for="Date"></label>
                    <input asp-for="Date" class="form-control" />
                </div>

                <div class="card-text form-group">
                    <label asp-for="Content"></label>
                    <input asp-for="Content" class="form-control" />
                </div>

                <input type="submit" value="Update" class="btn btn-success text-right" />
            </div>
        </div>
    </div>
</form>

WebUI/Views/Blog/List.cshtml
@model IEnumerable<Blog>

    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Blog List</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table class="table table-striped">
                    <thead class="bg-dark">
                        <tr>
                            <th>Category</th>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Date</th>
                            <th>Is Home</th>
                            <th>Is Approved</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var blog in Model)
                        {
                        <tr>
                            <td>
                                @await Component.InvokeAsync("GetCategoryName",blog.CategoryId)
                            </td>
                            <td>
                                <img src="~/img/@blog.Image" alt="@blog.Title" width="160" />
                            </td>
                            <td>@blog.Title</td>
                            <td>@blog.Description</td>
                            <td>@blog.Date</td>
                            <td>
                                @if (@blog.IsHome)
                                {
                                    <i class="fas fa-check"></i>
                                }
                                else
                                {
                                    <i class="fas fa-times"></i>
                                }
                            </td>
                            <td>
                                @if (@blog.IsApproved)
                                {
                                    <i class="fas fa-check"></i>
                                }
                                else
                                {
                                    <i class="fas fa-times"></i>
                                }
                            </td>
                            <td width="5%" class="bg-light">
                                <a asp-controller="Blog" asp-action="Edit" asp-route-id="@blog.Id"
                                   class="btn btn-sm btn-warning btn-outline-dark">
                                    Edit
                                </a>
                            </td>
                            <td width="5%" class="bg-light">
                                <a asp-controller="Blog" asp-action="Details" asp-route-id="@blog.Id"
                                   class="btn btn-sm btn-primary btn-outline-dark">
                                    Details
                                </a>
                            </td>
                            <td width="5%" class="bg-light">
                                <a asp-controller="Blog" asp-action="Delete" asp-route-id="@blog.Id"
                                   class="btn btn-sm btn-danger btn-outline-dark">
                                    Delete
                                </a>
                            </td>
                        </tr>
                        }


                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-right">
                    <li class="page-item"><a class="page-link" href="#">«</a></li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">»</a></li>
                </ul>
            </div>
        </div>
    </div>

WebUI/Views/Category/Create.cshtml
@model  Category

<form method="post" enctype="multipart/form-data">
    <div class="container">
        <div class="card card-primary card-outline">
            <div class="card-body">

                <div class="card-text form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                </div>
                <input type="submit" value="Add" class="btn btn-success text-right" />
            </div>
        </div>
    </div>
</form>

WebUI/Views/Category/Edit.cshtml
@model Category

    <form method="post" enctype="multipart/form-data">
        <div class="container">
            <div class="card card-primary card-outline">
                <div class="card-body">

                    <div class="card-text form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" />
                    </div>
                    <input type="submit" value="Update" class="btn btn-success text-right" />
                </div>
            </div>
        </div>
    </form>

WebUI/Views/Category/List.cshtml
@model IEnumerable<Category>

<div class="container">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Blog List</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table class="table table-striped">
                <thead class="bg-dark">
                    <tr>
                        <th>Name</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var category in Model)
                    {
                        <tr>
                            
                            <td>@category.Name</td>
                            
                            <td width="5%" class="bg-light">
                                <a asp-controller="Category" asp-action="Edit" asp-route-id="@category.Id"
                                   class="btn btn-sm btn-warning btn-outline-dark">
                                    Edit
                                </a>
                            </td>
                            <td width="5%" class="bg-light">
                                <a asp-controller="Category" asp-action="Details" asp-route-id="@category.Id"
                                   class="btn btn-sm btn-primary btn-outline-dark">
                                    Details
                                </a>
                            </td>
                            <td width="5%" class="bg-light">
                                <a asp-controller="Category" asp-action="Delete" asp-route-id="@category.Id"
                                   class="btn btn-sm btn-danger btn-outline-dark">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
        <div class="card-footer clearfix">
            <ul class="pagination pagination-sm m-0 float-right">
                <li class="page-item"><a class="page-link" href="#">«</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">»</a></li>
            </ul>
        </div>
    </div>
</div>

WebUI/Views/Home/Category.cshtml
@model IEnumerable<Blog>

<div class="container">
    <div class="row">
        <div class="col-9">
            @{ if (Model.Count() == 0)
                {
                    <div class="card card-default">

                        <div class="card-body">
                            <div class="alert alert-warning alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <h5><i class="icon fas fa-exclamation-triangle"></i> Uyarı!</h5>
                                Herhangi bir kayıt bulunamadı.
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                }
                else
                {
                    @foreach (var blog in Model)
                    {
                        <div class="card card-widget my-3">
                            <div class="card-header">

                                <div class="user-block">
                                    <img class="img-circle card-img" src="~/img/Pyhton3.png" alt="User Image">
                                    <span class="username"><a href="#">Rıdvan Abay</a></span>
                                    <span class="description">Shared publicly - 7:30 PM Today</span>
                                    <span class="description">   @await Component.InvokeAsync("GetCategoryName", blog.CategoryId)</span>

                                </div>
                            </div>
                            <div class="card-body">
                                <h3 class="card-title"><strong>@blog.Title</strong> </h3>

                                <p class="card-text">@blog.Description</p>
                                <a asp-controller="Home" asp-action="Details" asp-route-id="@blog.Id" class="btn btn-sm btn-outline-info">Details</a>
                            </div>
                            <div class="card-footer text-muted d-flex justify-content-between bg-transparent border-top-0">
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i> Share</button>
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
                                <span class="float-right text-muted">45 likes - 2 comments</span>
                            </div>
                        </div>
                    }
                }
            }


        </div>
        <div class="col-md-3">

        </div>
    </div>
</div>

WebUI/Views/Home/Details.cshtml
@model Blog

<div class="container">
    <div class="row">
        <div class="col-9">
            <div class="card card-widget my-3">
                <div class="card-header">

                    <div class="user-block">
                        <img class="img-circle card-img" src="~/img/Pyhton3.png" alt="User Image">
                        <span class="username"><a href="#">Rıdvan Abay</a></span>
                        <span class="description">Shared publicly - 7:30 PM Today</span>
                        <span class="description">   @await Component.InvokeAsync("GetCategoryName", Model.CategoryId)</span>

                    </div>
                </div>
                <div class="card-body">
                    <h3 class="card-title"><strong>@Model.Title</strong> </h3>

                    <p class="card-text">@Model.Description</p>
                </div>
                <div class="card-footer text-muted d-flex justify-content-between bg-transparent border-top-0">
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i> Share</button>
                    <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
                    <span class="float-right text-muted">45 likes - 2 comments</span>
                </div>
            </div>
        </div>
        <div class="col-3">
          
        </div>
      
    </div>
</div>

WebUI/Views/Home/Index.cshtml
@model IEnumerable<Blog>

<div class="container">
    <div class="row">
        <div class="col-9">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-9">
                        <div class="container-fluid">
                            <div class="row">
                                @foreach (var blog in Model)
                                {
                                    <div class="col-12">
                                        <div class="card card-widget">
                                            <div class="card-header">

                                                <div class="user-block">
                                                    <img class="img-circle card-img" src="~/img/@blog.Image" alt="User Image">
                                                    <span class="username"><a href="#">Rıdvan Abay</a></span>
                                                    <span class="description">@blog.Date.ToShortDateString()</span>
                                                    <span class="description">
                                                        @await Component.InvokeAsync("GetCategoryName", blog.CategoryId)
                                                    </span>


                                                </div>
                                            </div>
                                            <div class="card-body">
                                                <h3 class="card-title"><strong>@blog.Title</strong> </h3>

                                                <p class="card-text">@blog.Description</p>
                                                <a asp-controller="Home" asp-action="Details" asp-route-id="@blog.Id" class="btn btn-sm btn-outline-info">Devamını Oku</a>
                                            </div>
                                            @*<div class="card-footer text-muted d-flex justify-content-between bg-transparent border-top-0">
                                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i> Share</button>
                                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
                                                <span class="float-right text-muted">45 likes - 2 comments</span>
                                            </div>*@
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-3">
            @await Component.InvokeAsync("CategoryMenuRight")
        </div>
    </div>
</div>

WebUI/Views/Shared/Admin/_Footer.cshtml
<footer class="main-footer">
  
</footer>

WebUI/Views/Shared/Admin/_LeftMenu.cshtml
     <!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a asp-controller="Blog" asp-action="List" class="brand-link">
        <span class="brand-text font-weight-light">Admin Panel</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
         
            <div class="info">
                <a href="#" class="d-block">Rıdvan Abay</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview menu-open">
                    <a href="#" class="nav-link active">
                        <p>
                            Blogs
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Blog" asp-action="Create" class="nav-link">
                                <p>Create</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Blog" asp-action="List" class="nav-link">
                                <p>List</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview menu-open">
                    <a href="#" class="nav-link active">
                        <p>
                            Categories
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Category" asp-action="Create" class="nav-link">
                                <p>Create</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Category" asp-action="List" class="nav-link">
                                <p>List</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

WebUI/Views/Shared/Admin/_PageInfo.cshtml
 <!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Starter Page</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Starter Page</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

WebUI/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <div class="container">
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                @foreach (var category in Model)
                {
                <li class="nav-item ">
                    <a class="nav-link" asp-controller="Home" asp-action="Category" asp-route-id="@category.Id">@category.Name</a>
                </li>
                }
                
            </ul>
        </div>
    </div>
</nav>

WebUI/Views/Shared/_Navbar.cshtml
   <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Anasayfa</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item ">
                            <a class="nav-link" asp-action="List" asp-controller="Blog">
                                Admin
                            </a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link" href="#">Hakkımda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">İletişim</a>
                        </li>
                    </ul>
                </div>


               @await  Component.InvokeAsync("SearchBlog")
            </div>
        </nav>